services:
  app:
    container_name: book-dental-app-prod
    image: ghcr.io/zunkireelabs/book-dental:prod
    networks:
      - hosting
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    labels:
      - "autoheal=true"
      - "traefik.enable=true"
      - "traefik.docker.network=hosting"
      - "traefik.http.routers.book-dental-app-prod.rule=Host(`book-dental.zunkireelabs.com`)"
      - "traefik.http.routers.book-dental-app-prod.entrypoints=websecure"
      - "traefik.http.routers.book-dental-app-prod.tls=true"
      - "traefik.http.routers.book-dental-app-prod.tls.certresolver=letsencrypt"
      - "traefik.http.routers.book-dental-app-prod-http.rule=Host(`book-dental.zunkireelabs.com`)"
      - "traefik.http.routers.book-dental-app-prod-http.entrypoints=web"
      - "traefik.http.routers.book-dental-app-prod-http.middlewares=book-dental-app-prod-redirect"
      - "traefik.http.middlewares.book-dental-app-prod-redirect.redirectscheme.scheme=https"
      - "traefik.http.services.book-dental-app-prod.loadbalancer.server.port=80"

networks:
  hosting:
    external: true
